import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import { QueryProvider } from "@/components/QueryProvider";
import { Toaster } from "sonner";
import Script from "next/script";
import { GlobalActivityOverlay } from "@/components/GlobalActivityOverlay";
import { OmniPadDrawer } from "@/components/OmniPadDrawer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} dark h-full antialiased`}
    >
      <body className="h-screen w-screen flex flex-col overflow-hidden bg-zinc-950 text-zinc-50">
        <Script
          id="unhandled-rejections"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.addEventListener('unhandledrejection', function(event) {
                var r = event.reason;
                if (!r) return;
                var n = (r && r.name) ? String(r.name) : '';
                var m = (r && r.message) ? String(r.message) : String(r);
                var s = String(r);
                if (
                  n === 'Canceled' ||
                  m === 'Canceled' ||
                  s === 'Canceled' ||
                  s === 'Canceled: Canceled' ||
                  n === 'NotAllowedError' ||
                  m.includes('NotAllowedError') ||
                  m.includes('user agent or the platform in the current context') ||
                  m.includes('denied permission') ||
                  m.includes('disposed') ||
                  m.includes('TextModel') ||
                  n === 'AbortError' ||
                  m.includes('AbortError')
                ) {
                  event.preventDefault();
                  if (typeof event.stopImmediatePropagation === 'function') {
                    event.stopImmediatePropagation();
                  }
                }
              });

              window.addEventListener('error', function(event) {
                var m = (event && event.message) ? String(event.message) : '';
                var err = event && event.error;
                var n = (err && err.name) ? String(err.name) : '';
                if (
                  n === 'NotAllowedError' ||
                  m.includes('NotAllowedError') ||
                  m.includes('user agent or the platform in the current context') ||
                  m.includes('denied permission') ||
                  m.includes('Canceled: Canceled') ||
                  m.includes('disposed')
                ) {
                  event.preventDefault();
                  if (typeof event.stopImmediatePropagation === 'function') {
                    event.stopImmediatePropagation();
                  }
                }
              });
            `,
          }}
        />
        <QueryProvider>
          <ThemeProvider>
            <main className="flex-1 overflow-hidden flex flex-col relative">
              {children}
            </main>
          </ThemeProvider>
        </QueryProvider>
        <GlobalActivityOverlay />
        <OmniPadDrawer />
        <Toaster theme="dark" position="bottom-right" />
      </body>
    </html>
  );
}
