import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";
import { QueryProvider } from "@/components/QueryProvider";
import { Toaster } from "sonner";
import Script from "next/script";
import { GlobalActivityOverlay } from "@/components/GlobalActivityOverlay";
import { StatusBar } from "@/components/StatusBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="h-screen w-screen flex flex-col overflow-hidden bg-zinc-950 text-zinc-50">
        <Script
          id="unhandled-rejections"
          dangerouslySetInnerHTML={{
            __html: `
              window.addEventListener('unhandledrejection', function(event) {
                var r = event.reason;
                if (!r) return;
                var n = r.name || '';
                var m = r.message || '';
                if (n === 'Canceled' || m === 'Canceled' || m.includes('disposed') || m.includes('TextModel') || n === 'AbortError') {
                  event.preventDefault();
                }
              });
            `,
          }}
        />
        <QueryProvider>
          <ThemeProvider>
            <main className="flex-1 overflow-hidden flex flex-col relative">
              {children}
            </main>
          </ThemeProvider>
        </QueryProvider>
        <GlobalActivityOverlay />
        <StatusBar />
        <Toaster theme="dark" position="bottom-right" />
      </body>
    </html>
  );
}
