"""SQLite Sidecar Schema

Revision ID: 15a94234a707
Revises:
Create Date: 2026-07-17 21:58:47.463349

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15a94234a707'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adr_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filepath', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('breadcrumbs', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daemon_locks',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('last_fired_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('project_id', 'rule')
    )
    op.create_table('project_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('agent_name', sa.String(), nullable=True),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('memory_content', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('last_opened', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('line', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telemetry_pings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('window_start_ms', sa.BigInteger(), nullable=False),
    sa.Column('window_end_ms', sa.BigInteger(), nullable=False),
    sa.Column('thinking_ms', sa.BigInteger(), nullable=False),
    sa.Column('coding_ms', sa.BigInteger(), nullable=False),
    sa.Column('testing_ms', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_memories_topic'), ['topic'], unique=False)

    op.create_table('analysis_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('ai_model_version', sa.String(length=50), nullable=False),
    sa.Column('structural_metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_reports_project_id'), ['project_id'], unique=False)

    op.create_table('ast_node_map',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('fqn', sa.String(length=1024), nullable=False),
    sa.Column('node_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ast_node_map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ast_node_map_fqn'), ['fqn'], unique=False)
        batch_op.create_index(batch_op.f('ix_ast_node_map_node_hash'), ['node_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ast_node_map_project_id'), ['project_id'], unique=False)

    op.create_table('context_snippets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_project_id'), ['project_id'], unique=False)

    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Enum('FILE', 'CLASS', 'FUNCTION', name='nodelabel'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('meta_data', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('loc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_nodes_project_id'), ['project_id'], unique=False)

    op.create_table('graph_edges',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('IMPORTS', 'CALLS', 'CONTAINS', name='edgetype'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'source_id', 'target_id', 'type')
    )
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_project_id'), ['project_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_project_id'))

    op.drop_table('graph_edges')
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_project_id'))

    op.drop_table('graph_nodes')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_project_id'))

    op.drop_table('conversations')
    op.drop_table('context_snippets')
    with op.batch_alter_table('ast_node_map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ast_node_map_project_id'))
        batch_op.drop_index(batch_op.f('ix_ast_node_map_node_hash'))
        batch_op.drop_index(batch_op.f('ix_ast_node_map_fqn'))

    op.drop_table('ast_node_map')
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_reports_project_id'))

    op.drop_table('analysis_reports')
    with op.batch_alter_table('ai_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_memories_topic'))
        batch_op.drop_index(batch_op.f('ix_ai_memories_created_at'))

    op.drop_table('ai_memories')
    op.drop_table('users')
    op.drop_table('telemetry_pings')
    op.drop_table('search_index')
    op.drop_table('projects')
    op.drop_table('project_memories')
    op.drop_table('daemon_locks')
    op.drop_table('adr_chunks')
    # ### end Alembic commands ###
