"""add subtasks relationship and parent_id column

Revision ID: 28f7b3c6d454
Revises: e266a18a4c13
Create Date: 2026-08-10 20:05:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "28f7b3c6d454"
down_revision: str | Sequence[str] | None = "e266a18a4c13"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.UUID(), nullable=True))
        batch_op.create_foreign_key(
            "fk_kanban_tickets_parent_id",
            "kanban_tickets",
            ["parent_id"],
            ["id"],
            ondelete="CASCADE",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_kanban_tickets_parent_id", "kanban_tickets", type_="foreignkey"
        )
        batch_op.drop_column("parent_id")

    # ### end Alembic commands ###
