"""Add doc_bookmarks table

Revision ID: 3f1715d46a79
Revises: ee37f2160dee
Create Date: 2026-07-30 12:28:36.097968

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f1715d46a79"
down_revision: str | Sequence[str] | None = "ee37f2160dee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "custom_llm_providers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("base_url", sa.String(length=1024), nullable=True),
        sa.Column("keyring_service_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doc_bookmarks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("selected_text", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("doc_bookmarks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doc_bookmarks_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("analysis_reports", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=50),
            nullable=False,
            existing_server_default=sa.text("'code_analysis'"),
        )

    with op.batch_alter_table("schema_drafts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_schema_drafts_project_id"), ["project_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schema_drafts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schema_drafts_project_id"))

    with op.batch_alter_table("analysis_reports", schema=None) as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.VARCHAR(length=50),
            nullable=True,
            existing_server_default=sa.text("'code_analysis'"),
        )

    with op.batch_alter_table("doc_bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doc_bookmarks_project_id"))

    op.drop_table("doc_bookmarks")
    op.drop_table("custom_llm_providers")
    # ### end Alembic commands ###
