"""add epic and sprint entities with soft delete

Revision ID: 5e8b2ba0e267
Revises: 28f7b3c6d454
Create Date: 2026-08-11 17:34:08.323301

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e8b2ba0e267"
down_revision: str | Sequence[str] | None = "28f7b3c6d454"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epics",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("color", sa.String(length=50), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "ARCHIVED", name="epicstatus"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("epics", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_epics_project_id"), ["project_id"], unique=False)

    op.create_table(
        "sprints",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PLANNED", "ACTIVE", "COMPLETED", "ARCHIVED", name="sprintstatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sprints", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sprints_project_id"), ["project_id"], unique=False)

    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("epic_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("sprint_id", sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f("ix_kanban_tickets_epic_id"), ["epic_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_kanban_tickets_sprint_id"), ["sprint_id"], unique=False
        )
        batch_op.drop_constraint(batch_op.f("fk_kanban_tickets_parent_id"), type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_kanban_tickets_sprint_id", "sprints", ["sprint_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.create_foreign_key(
            "fk_kanban_tickets_epic_id", "epics", ["epic_id"], ["id"], ondelete="SET NULL"
        )
        batch_op.drop_column("sprint")
        batch_op.drop_column("parent_id")
        batch_op.drop_column("epic")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("epic", sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column("parent_id", sa.NUMERIC(), nullable=True))
        batch_op.add_column(sa.Column("sprint", sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint("fk_kanban_tickets_epic_id", type_="foreignkey")
        batch_op.drop_constraint("fk_kanban_tickets_sprint_id", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_kanban_tickets_parent_id"),
            "kanban_tickets",
            ["parent_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_index(batch_op.f("ix_kanban_tickets_sprint_id"))
        batch_op.drop_index(batch_op.f("ix_kanban_tickets_epic_id"))
        batch_op.drop_column("sprint_id")
        batch_op.drop_column("epic_id")

    with op.batch_alter_table("sprints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sprints_project_id"))

    op.drop_table("sprints")
    with op.batch_alter_table("epics", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_epics_project_id"))

    op.drop_table("epics")
    # ### end Alembic commands ###
