"""Refactor to UniversalBookmarkModel

Revision ID: 69976f5b0dbd
Revises: a680d8f462b9
Create Date: 2026-07-30 19:59:45.667090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69976f5b0dbd"
down_revision: str | Sequence[str] | None = "a680d8f462b9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "universal_bookmarks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=False),
        sa.Column("selected_text", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("item_type", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("universal_bookmarks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_universal_bookmarks_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("doc_bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_doc_bookmarks_project_id"))

    op.drop_table("doc_bookmarks")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doc_bookmarks",
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("project_id", sa.CHAR(length=32), nullable=False),
        sa.Column("file_path", sa.VARCHAR(length=1024), nullable=False),
        sa.Column("selected_text", sa.TEXT(), nullable=False),
        sa.Column("note", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("doc_bookmarks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_doc_bookmarks_project_id"), ["project_id"], unique=False
        )

    with op.batch_alter_table("universal_bookmarks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_universal_bookmarks_project_id"))

    op.drop_table("universal_bookmarks")
    # ### end Alembic commands ###
