"""align kanban ticket default type to Feature

Revision ID: 6e2442813928
Revises: c8ce1ffddd4d
Create Date: 2026-08-16 20:48:07.422618

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '6e2442813928'
down_revision: str | Sequence[str] | None = 'c8ce1ffddd4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
