"""add graph models

Revision ID: 9ef762f3539a
Revises: 914f7f90ce02
Create Date: 2026-06-28 22:51:06.097906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef762f3539a'
down_revision: Union[str, Sequence[str], None] = '914f7f90ce02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_nodes',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.Enum('FILE', 'CLASS', 'FUNCTION', name='nodelabel'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('target_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('IMPORTS', 'CALLS', 'CONTAINS', name='edgetype'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('source_id', 'target_id', 'type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_edges')
    op.drop_table('graph_nodes')
    # ### end Alembic commands ###
