"""Add OmniNoteModel

Revision ID: a680d8f462b9
Revises: 3f1715d46a79
Create Date: 2026-07-30 16:07:16.491231

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a680d8f462b9"
down_revision: str | Sequence[str] | None = "3f1715d46a79"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "omni_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("omni_notes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_omni_notes_project_id"), ["project_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("omni_notes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_omni_notes_project_id"))

    op.drop_table("omni_notes")
    # ### end Alembic commands ###
