"""add meta_data to graph nodes

Revision ID: ae848f9ff63a
Revises: 8fdd7667e3f4
Create Date: 2026-06-29 20:08:54.808650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae848f9ff63a'
down_revision: Union[str, Sequence[str], None] = '8fdd7667e3f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('graph_nodes', sa.Column('meta_data', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graph_nodes', 'meta_data')
    # ### end Alembic commands ###
