"""add_kanban_tables

Revision ID: e0bd0a4793b9
Revises: 3d47752804c6
Create Date: 2026-07-23 17:27:56.384512

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0bd0a4793b9"
down_revision: str | Sequence[str] | None = "3d47752804c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kanban_tickets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("report_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "type",
            sa.Enum("TECHNICAL_DEBT", "SECURITY", "REFACTOR", "FEATURE", name="tickettype"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("TODO", "IN_PROGRESS", "DONE", "ARCHIVED", name="ticketstatus"),
            nullable=False,
        ),
        sa.Column(
            "priority", sa.Enum("HIGH", "MEDIUM", "LOW", name="ticketpriority"), nullable=False
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["analysis_reports.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_kanban_tickets_project_id"), ["project_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_kanban_tickets_report_id"), ["report_id"], unique=False
        )

    op.create_table(
        "kanban_ticket_nodes",
        sa.Column("ticket_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["node_id"], ["graph_nodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["ticket_id"], ["kanban_tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("ticket_id", "node_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kanban_ticket_nodes")
    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_kanban_tickets_report_id"))
        batch_op.drop_index(batch_op.f("ix_kanban_tickets_project_id"))

    op.drop_table("kanban_tickets")
    # ### end Alembic commands ###
