"""add sprint center columns

Revision ID: e266a18a4c13
Revises: 3473b1a887cc
Create Date: 2026-08-10 16:41:56.160935

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e266a18a4c13"
down_revision: str | Sequence[str] | None = "3473b1a887cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.add_column(sa.Column("branch_name", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("epic", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("sprint", sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column("subtasks", sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kanban_tickets", schema=None) as batch_op:
        batch_op.drop_column("subtasks")
        batch_op.drop_column("sprint")
        batch_op.drop_column("epic")
        batch_op.drop_column("branch_name")

    # ### end Alembic commands ###
