"""add structural_metrics to analysis_reports

Revision ID: e785b38accca
Revises: f61661b931e5
Create Date: 2026-07-11 13:05:59.858816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e785b38accca'
down_revision: Union[str, Sequence[str], None] = 'f61661b931e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('structural_metrics', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_reports', schema=None) as batch_op:
        batch_op.drop_column('structural_metrics')
    # ### end Alembic commands ###
