"""Add DeveloperInsightModel

Revision ID: f179ff5774c5
Revises: 88ac0deb7f74
Create Date: 2026-07-18 15:26:40.501005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f179ff5774c5'
down_revision: Union[str, Sequence[str], None] = '88ac0deb7f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developer_insights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('sintoma', sa.String(), nullable=False),
    sa.Column('solucion', sa.String(), nullable=False),
    sa.Column('snippet_corregido', sa.String(), nullable=True),
    sa.Column('embedding_blob', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('developer_insights')
    # ### end Alembic commands ###
