"""fix(db): add missing indexes and enforce uuid foreign keys

Revision ID: f61661b931e5
Revises: fad7bbd2835e
Create Date: 2026-07-01 20:13:19.757022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f61661b931e5'
down_revision: Union[str, Sequence[str], None] = 'fad7bbd2835e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_memories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_memories_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_memories_topic'), ['topic'], unique=False)

    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_edges_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_nodes_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_nodes_project_id'))

    with op.batch_alter_table('graph_edges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_edges_project_id'))

    with op.batch_alter_table('ai_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_memories_topic'))
        batch_op.drop_index(batch_op.f('ix_ai_memories_created_at'))

    # ### end Alembic commands ###
