"""rename jarvis to ai and add project_id to graph

Revision ID: fad7bbd2835e
Revises: ae848f9ff63a
Create Date: 2026-06-30 11:28:44.140608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fad7bbd2835e'
down_revision: Union[str, Sequence[str], None] = 'ae848f9ff63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('jarvis_memories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jarvis_memories',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.CHAR(length=32), nullable=True),
    sa.Column('memory_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ai_memories')
    # ### end Alembic commands ###
