from typing import Protocol
from uuid import UUID

from app.domain.graph_models import GraphEdge, GraphNode


class GraphRepository(Protocol):
    async def save_nodes(self, nodes: list[GraphNode]) -> None: ...

    async def save_edges(self, edges: list[GraphEdge]) -> None: ...

    async def clear_by_project(self, project_id: UUID) -> None: ...

    async def get_nodes_by_project(self, project_id: UUID) -> list[GraphNode]: ...

    async def get_edges_by_project(self, project_id: UUID) -> list[GraphEdge]: ...

    async def get_blast_radius(self, project_id: UUID, target_node_id: str, max_depth: int = 2) -> list[dict]: ...
